  # Set the en_GB locale
      - name: generate language
        become: yes
        shell: locale-gen en_GB en_GB.UTF-8
       - name: set LANG
        become: yes
        shell: update-locale LANG='en_GB.UTF-8'
       - name: set LANGUAGE
        become: yes
        shell: update-locale LANGUAGE='en_GB.UTF-8'
       - name: set LC_ALL
        become: yes
        shell: update-locale LC_ALL='en_GB.UTF-8'
       - name: reload locale
        shell: . /etc/default/locale
       - name: Install git
        become: yes
        apt:
          name: git
          state: latest
          
   # Install PostgreSQL
      - name: Install PostgreSQL
        become: yes
        apt: 
          name: "{{ item }}"
          state: latest
          update_cache: yes
        with_items:
          - postgresql
          - postgis
          - pgadmin3
          - postgresql-contrib
          
   # Set the password for the postgres user
      - name: create a file
        copy:
          content: 'localhost:5432:*:postgres:postgres_007%'
          dest: /home/ubuntu/.pgpass
          mode: 0600
        
      - name: trust
        become: yes
        shell: sed -i 's|peer|trust|' /etc/postgresql/10/main/pg_hba.conf
        args:
          warn: no
            
      - name: trust (2)
        become: yes
        shell: sed -i 's|md5|trust|' /etc/postgresql/10/main/pg_hba.conf
        args:
          warn: no
            
      - name: restart postgresql
        become: yes
        service: 
          name: postgresql 
          state: restarted
 # ------------------ backup -------------------
      #create a dump file
      - name: create a dump file
        file:
          path: /etc/
          state: directory 
          mode: 0755
       
       #back up file
       - name: pgdump
         shell: pg_dump -F c -f ~/backup/gis_backup.dmp  -C -E  UTF8 -h %actual_ip% -p 5432 -U postgres gis
         
# ------------------ restore -------------------
      # Create the postgis and hstore extensions
      - name: connect gis
        shell: psql -U postgres -h localhost -c "\connect gis"
        register: connect_gis
        failed_when: connect_gis.rc != 1 and connect_gis.rc != 0
      
      - name: hstore extension
        command: psql -U postgres -h localhost -d gis -c "CREATE EXTENSION {{ item }}"
        with_items:
          - postgis
          - hstore
       - name: Add a user and grant access to gis DB
        postgresql_user:
          db: "{{ db_name }}"
          name: ubuntu
          priv: ALL
       
      - name: Enabling remote access to PostgreSQL (1)
        become: yes
        lineinfile:
          path: /etc/postgresql/10/main/pg_hba.conf
          line: 'host all all 0.0.0.0/0 trust'
            
      - name: Enabling remote access to PostgreSQL (2)
        become: yes
        lineinfile:
          path: /etc/postgresql/10/main/postgresql.conf
          line: "listen_addresses = '*'"
      
      - name: restart postgresql
        become: yes
        service: 
          name: postgresql
          state: restarted
         
 #Tuning the database
       - name: Tuning the database
        become: yes
        lineinfile:
          path: /etc/postgresql/10/main/postgresql.conf
          line: "{{ item }}"
        with_items:
          - 'shared_buffers = 128MB'
          - 'min_wal_size = 80MB'
          - 'max_wal_size = 1GB'
          - 'work_mem = 4MB'
          - 'maintenance_work_mem= 64MB'
          - 'autovacuum = off'
          - 'fsync = off'
       - name: stop postgresql
        become: yes
        shell: /etc/init.d/postgresql stop
       - name: start postgresql
        become: yes
        shell: /etc/init.d/postgresql start
        
 # Restore
 
      - name: restore database
        shell: pg_dump -F c -f ~/backup/gis_backup.dmp  -C -E  UTF8 -h %actual_ip% -p 5432 -U postgres gis
