# configure_renderd.yml
#
# Author: Simon Freeman 22/Aug/2018
#
# Description: Configure and install renderd
#

---	
# Configure renderd
- name: Configure rendered(1) socketname
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: renderd
		option: socketname
		value: /var/run/renderd/renderd.sock

- name: Configure rendered(2) plugins_dir
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: mapnik
		option: plugins_dir
		value: /usr/lib/mapnik/3.0/input/

- name: Configure rendered(3) font_dir
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: mapnik
		option: font_dir
		value: /usr/share/fonts

- name: Configure rendered(4) font_dir_recurse
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: mapnik
		option: font_dir_recurse
		value: true

- name: Configure rendered(5) URI
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: default
		option: URI
		value: /osm_tiles/

- name: Configure rendered(6) XML
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: default
		option: XML
		value: /home/ubuntu/src/openstreetmap-carto/style.xml

- name: Configure rendered(7) HOST
	ini_file:
		path: /usr/local/etc/renderd.conf
		section: default
		option: HOST
		value: localhost


# Install renderd init script by copying the sample init script included in its package
- name: install renderd(1)
	action: copy src=~/src/mod_tile/debian/renderd.init dest: /etc/init.d/postgresql
    
- name: install renderd(2)
	script: chmod a+x /etc/init.d/renderd
		


# Edit the init script file - THIS STILL NEEDS CONVERTING. I considered using lineinfile but struggled a bit
#- name: Configure init(1) DAEMON
#	lineinfile:
#		path: /etc/init.d/renderd
#		regexp: ''
#		line: ''

- name: Edit script(1)
	script: sed -i -e '/DAEMON=/ s~=.*~= /usr/local/bin/$NAME~' /etc/init.d/renderd
      
- name: Edit script(2)
	script: sed -i -e '/DAEMON_ARGS=/ s~=.*~= "-c /usr/local/etc/renderd.conf"~' /etc/init.d/renderd
      
- name: Edit script(3)
	script: sed -i -e '/RUNASUSER=/ s~=.*~=ubuntu~' /etc/init.d/renderd


# Create directories for renderd and mod_tile
- name: creates directory for renderd
	file: path=/var/run/renderd
	state: directory
	mode: 0755 #not suee if needed?

- name: set owner for renderd
	script: chown ubuntu:ubuntu /var/run/renderd

	
- name: creates directory for mod_tile
	file: path=/var/run/renderd
	state: directory
	mode: 0755 #not suee if needed?

- name: set owner for renderd
	script: chown ubuntu:ubuntu /var/lib/mod_tile

# Load and enable renderd
- name: daemon reload 
     script: systemctl daemon-reload
    
    -name: start renderd
     script: systemctl start renderd
      
    -name: enable renderd
     script: systemctl enable renderd

...
