# configure_renderd.yml
#
# Author: Simon Freeman 22/Aug/2018
#
# Description: Configure renderd test file
#

# Configure renderd
# sudo sed -i "2i\socketname=/var/run/renderd/renderd.sock" /usr/local/etc/renderd.conf
# sudo sed -i -e '/plugins_dir/ s~=.*~=/usr/lib/mapnik/3.0/input~' /usr/local/etc/renderd.conf
# sudo sed -i -e '/font_dir=/ s~=.*~=/usr/share/fonts~' /usr/local/etc/renderd.conf
# sudo sed -i -e '/font_dir_recurse=/ s~=.*~=true~' /usr/local/etc/renderd.conf
# sudo sed -i -e '/URI=/ s~=.*~=/osm_tiles/~' /usr/local/etc/renderd.conf
# sudo sed -i -e '/XML=/ s~=.*~=/home/ubuntu/src/openstreetmap-carto/style.xml~' /usr/local/etc/renderd.conf
# sudo sed -i -e '/HOST=/ s~=.*~=localhost~' /usr/local/etc/renderd.conf

# Install renderd init script by copying the sample init script included in its package
# sudo cp ~/src/mod_tile/debian/renderd.init /etc/init.d/renderd
# sudo chmod a+x /etc/init.d/renderd

# Edit the init script file
# sudo sed -i -e '/DAEMON=/ s~=.*~= /usr/local/bin/$NAME~' /etc/init.d/renderd
# sudo sed -i -e '/DAEMON_ARGS=/ s~=.*~= "-c /usr/local/etc/renderd.conf"~' /etc/init.d/renderd
# sudo sed -i -e '/RUNASUSER=/ s~=.*~=ubuntu~' /etc/init.d/renderd

# sudo mkdir /var/run/renderd
# sudo chown ubuntu:ubuntu /var/run/renderd

# sudo mkdir -p /var/lib/mod_tile
# sudo chown ubuntu:ubuntu /var/lib/mod_tile

# sudo systemctl daemon-reload
# sudo systemctl start renderd
# sudo systemctl enable renderd

---

...
