# Configure a swap ()
- hosts: web001
  tasks:
- name: create the file to be used for swap
  command: fallocate -l 4G /swapfile

- name: format the file for swap
  command: mkswap /swapfile

- name: change swap file permissions
  file: path=/swapfile owner=root group=root mode=0600

- name: add the file to the system as a swap file
  command: swapon /swapfile

- name: write swap entry in fstab
  mount: name=none /swapfile fstype=swap opts=sw passno=0 dump=0 state=present
  
# Set the en_GB locale
- name: Set the locale and the time zone
  hosts: myhosts
  sudo: True
  vars:
    locale: en_GB.UTF-8
    timezone: NewZealand/Auckland

  tasks:
    - name: set locale
      command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL=$locale
    - name: set /etc/localtime
      file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
    - name: set /etc/timezone
      template: src=templates/etc/timezone dest=/etc/timezone
      notify: update tzdata

  handlers:
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

      
# Install openstreetmap-carto      
- git:
    repo: 'https://github.com/gravitystorm/openstreetmap-carto.git'
    dest: /src
    version: release-16.04     
# Install the fonts needed by openstreetmap-carto
#git clone https://github.com/googlei18n/noto-emoji.git
--Example git checkout from Ansible Playbooks
- git:
    repo: 'https://github.com/googlei18n/noto-emoji.git'
    dest: /src
    version: release-16.04

-- Example read-write git checkout from github
- git:
    repo: https://github.com/googlei18n/noto-emoji.git
    dest: /src

-- Example just ensuring the repo checkout exists
- git:
    repo: 'https://github.com/googlei18n/noto-emoji.git'
    dest: /src
    update: no

--Example just get information about the repository whether or not it has
-- already been cloned locally.
- git:
    repo: 'https://github.com/googlei18n/noto-emoji.git'
    dest: /src
    clone: no
    update: no

-- Example checkout a github repo and use refspec to fetch all pull requests
- git:
    repo: https://github.com/googlei18n/noto-emoji.git
    dest: /src
    refspec: '+refs/pull/*:refs/heads/*'

#git clone https://github.com/googlei18n/noto-fonts.git
--Example git checkout from Ansible Playbooks
- git:
    repo: 'https://github.com/googlei18n/noto-fonts.git'
    dest: /src
    version: release-16.04

-- Example read-write git checkout from github
- git:
    repo: https://github.com/googlei18n/noto-fonts.git
    dest: /src

-- Example just ensuring the repo checkout exists
- git:
    repo: 'https://github.com/googlei18n/noto-fonts.git'
    dest: /src
    update: no

--Example just get information about the repository whether or not it has
-- already been cloned locally.
- git:
    repo: 'https://github.com/googlei18n/noto-fonts.git'
    dest: /src
    clone: no
    update: no

-- Example checkout a github repo and use refspec to fetch all pull requests
- git:
    repo: https://github.com/googlei18n/noto-fonts.git
    dest: /src
    refspec: '+refs/pull/*:refs/heads/*'

